authors:
- Ansible
dependencies: {}
description: Bulk test collection tnsbabf21.tc179c3a6b (based on ansible.utils)
license:
- GPL-2.0-or-later
name: tc179c3a6b
namespace: tnsbabf21
readme: README.md
repository: https://github.com/test/tnsbabf21.tc179c3a6b
tags:
- networking
version: 6.0.2
